name: 'Build docs'
description: "Action that runs pants to package changed packages"
inputs:
  package:
    description: "Package name"
    required: true
  folder:
    description: "Package folder"
    required: true
  GITHUB_TOKEN:
    description: "GH token"
    required: true
runs:
  using: "composite"
  steps:
#    - uses: actions/checkout@v3
#      with:
#        fetch-depth: 0
    - uses: actions/setup-python@v4
      with:
        python-version: '3.7'
    - name: Install dependencies
      shell: bash
      run: |
        pip install sphinx sphinx_rtd_theme lowdown
    - name: Sphinx build
      shell: bash
      run: |
        ls -la
        ls ${{ inputs.folder }}
        ls ${{ inputs.folder }}/${{ inputs.package }}
        cd ${{ inputs.folder }}/${{ inputs.package }}
        sphinx-build doc public
#    - name: Deploy
#      uses: peaceiris/actions-gh-pages@v3
#      #if: ${{ contains(needs.probe.outputs.changed,matrix.package) }}
#      # Todo: uncheck this when you are ready to only deploy from main
#      #if: ${{ github.ref == 'refs/heads/main' }}
#      with:
#        # Todo: Change to gh-pages when you are ready
#        publish_branch: gh-pages
#        github_token: ${{ inputs.GITHUB_TOKEN }}
#        publish_dir: ${{ inputs.folder }}/${{ inputs.package }}/public
#        keep_files: true
#        destination_dir: ${{ inputs.folder }}/${{ inputs.package }}