[GLOBAL]
pants_version = "2.16.0"

build_patterns = ["*.pants", "BUILD_PANTS"]

backend_packages = [
  "pants.backend.python",
  "pants.backend.python.lint.black",
  "pants.backend.build_files.fmt.black",
  # "pants.backend.experimental.python.lint.ruff"
]

pants_ignore = ["/installers/*", "/tools/*"]

[source]
#marker_filenames = ["setup.py"]
root_patterns = [
  '/apps/',
  '/libs/',
  '/projects/',
]

[python-bootstrap]
search_path = [
    # This will use all interpreters in `$(pyenv root)/versions`.
    "<PYENV>",
    "<PATH>"
]

[setup-py-generation]
generate_setup_default = false

[anonymous-telemetry]
enabled = false