# :coding: utf-8
# :copyright: Copyright (c) 2019 ftrack

UNKNOWN_STATUS = 'UNKONWN_STATUS'
SUCCESS_STATUS = 'SUCCESS_STATUS'
WARNING_STATUS = 'WARNING_STATUS'
ERROR_STATUS   = 'ERROR_STATUS'
EXCEPTION_STATUS = 'EXCEPTION_STATUS'
RUNNING_STATUS = 'RUNNING_STATUS'
DEFAULT_STATUS = 'PAUSE_STATUS'

status_bool_mapping = {
    UNKNOWN_STATUS: False,
    SUCCESS_STATUS: True,
    WARNING_STATUS: False,
    ERROR_STATUS: False,
    EXCEPTION_STATUS: False,
    RUNNING_STATUS: False,
    DEFAULT_STATUS: False,
}