#! /usr/bin/env python
# :coding: utf-8
# :copyright: Copyright (c) 2019 ftrack


from ftrack_connect_pipeline_qt.client import QtClient
from ftrack_connect_pipeline.client.asset_manager import AssetManagerClient
from Qt import QtWidgets, QtCore, QtCompat, QtGui
from ftrack_connect_pipeline_qt.ui.utility.widget import header, host_selector
from ftrack_connect_pipeline_qt.ui.asset_manager import AssetManagerWidget

class QtAssetManagerClient(AssetManagerClient, QtWidgets.QWidget):
    '''
    Base load widget class.
    '''
    definition_filter = 'asset_manager'

    def __init__(self, event_manager, parent=None):
        QtWidgets.QWidget.__init__(self, parent=parent)
        AssetManagerClient.__init__(self, event_manager)

        # TODO: remove ftrack_asset_list
        self.asset_manager_widget = AssetManagerWidget(event_manager)

        self.pre_build()
        self.build()
        self.post_build()
        self.add_hosts(self.discover_hosts())

    def add_hosts(self, hosts):
        for host in hosts:
            if host in self.hosts:
                continue
            self._host_list.append(host)

    def _host_discovered(self, event):
        '''callback, adds new hosts connection from the given *event* to the
        host_selector'''
        super(AssetManagerClient, self)._host_discovered(event)
        self.host_selector.add_hosts(self.hosts)

    def pre_build(self):
        '''Prepare general layout.'''
        layout = QtWidgets.QVBoxLayout()
        self.setLayout(layout)

    def build(self):
        '''Build widgets and parent them.'''
        self.header = header.Header(self.session)
        self.layout().addWidget(self.header)

        self.host_selector = host_selector.HostSelector()
        self.layout().addWidget(self.host_selector)

        self.scroll = QtWidgets.QScrollArea()
        self.scroll.setWidgetResizable(True)
        self.layout().addWidget(self.scroll)

        # self.run_button = QtWidgets.QPushButton('Run')
        # self.layout().addWidget(self.run_button)

    def post_build(self):
        '''Post Build ui method for events connections.'''
        self.host_selector.host_changed.connect(self._host_changed)

        self.asset_manager_widget.widget_status_updated.connect(
            self._on_widget_status_updated
        )

    def _on_widget_status_updated(self, data):
        ''' Triggered when a widget generated by the fabric has emit the
        widget_status_update signal.
        Sets the status from the given *data* to the header
        '''
        status, message = data
        self.header.setMessage(message, status)

    def _host_changed(self, host_connection):
        ''' Triggered when definition_changed is called from the host_selector.
        Generates the widgets interface from the given *host_connection*,
        *schema* and *definition*'''
        print "------"
        if not host_connection:
            return

        self.logger.info('connection {}'.format(host_connection))
        self.host_connection = host_connection

        self.asset_manager_widget.set_host_connection(self.host_connection)
        self.asset_manager_widget.add_asset_list(
            self.discover_assets(self.host_connection.id)
        )

        self.scroll.setWidget(self.asset_manager_widget)