[tool.poetry]
name = "ftrack-framework-nuke"
version = "24.6.0"
description='ftrack Adobe Photoshop integration'
authors = ["ftrack Integrations Team <integrations@backlight.co>"]
readme = "README.md"
packages = [{include = "ftrack_framework_nuke", from = "source"}]
license = "Apache-2.0"
homepage = "https://ftrack.com"
repository = "https://github.com/ftrackhq/integrations/tree/main/projects/framework-nuke"

[[tool.poetry.source]]
name = "PyPI"
priority = "primary"

[[tool.poetry.source]]
name = "testpypi"
url = "https://test.pypi.org/simple/"
priority = "explicit"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.dependencies]
python = ">= 3.7, < 3.11"
ftrack-python-api = "^2.5.4"
# ftrack dependencies
ftrack-constants = {  version = "^3.0.0", optional = true }
ftrack-utils = {  version = "^3.0.0", optional = true }
# framework dependencies
ftrack-framework-core = {  version = "^3.0.0", optional = true}
ftrack-framework-qt = {  version = "^3.0.0", optional = true }
ftrack-qt = { version = "^3.0.0", optional = true }
ftrack-qt-style = { version = "^3.0.0", optional = true }

[tool.poetry.group.dev]
optional = true

# TODO: activate this and install using poetry install --with dev if you want to pick dependencies from local
[tool.poetry.group.dev.dependencies]
#ftrack-constants = { path = "../../libs/constants",  develop = true }
#ftrack-utils = { path = "../../libs/utils",  develop = true }
#ftrack-framework-core = { path = "../../libs/framework-core",  develop = true }
#ftrack-framework-qt = { path = "../../libs/framework-qt",  develop = true }
#ftrack-qt = { path = "../../libs/qt",  develop = true }
#ftrack-qt-style = { path = "../../libs/qt-style", develop = true }

[tool.poetry.group.testPypi]
optional = true

# TODO: activate this and install using poetry install --with testPypi if you want to pick dependencies from test pypi
[tool.poetry.group.testPypi.dependencies]
#ftrack-constants = { version = "^2.0.0", source = "testpypi" }
#ftrack-utils = { version = "^2.0.0", source = "testpypi" }
#ftrack-framework-core = { version = "^2.0.0", source = "testpypi" }
#ftrack-framework-qt = { version = "^2.0.0", source = "testpypi" }
#ftrack-qt = { version = "^2.0.0", source = "testpypi" }
#ftrack-qt-style = { version = "^2.0.0", source = "testpypi" }


[tool.poetry.extras]
ftrack-libs = ["ftrack-constants", "ftrack-utils", "ftrack-qt", "ftrack-qt-style"]
framework-libs = ["ftrack-framework-core", "ftrack-framework-qt"]

[tool.poetry.group.documentation]
optional = true

[tool.poetry.group.documentation.dependencies]
markdown = "<=3.2.2"

[tool.black]
line-length = 79
skip-string-normalization = true

