[tool.poetry]
name = "ftrack-connect-pipeline-harmony"
version = "0.0.0"
description='ftrack Connect pipeline framework Toon Boom Harmony integration'
authors = ["ftrack Integrations Team <integrations@backlight.co>"]
readme = "README.md"
packages = [{include = "ftrack_connect_pipeline_harmony"}]
license = "Apache-2.0"
maintainers = [
    "LLuis Casals <lluis.casals@backlight.co>",
    "Henrik Norin <henrik.norin@backlight.co>",
]
homepage = "https://ftrack.com"
repository = "https://github.com/ftrackhq/pipeline-integrations"

[tool.poetry.dependencies]
python = ">= 3.7, < 3.10"
pyffmpeg = ">= 2.4"

[build-system]
requires = ["poetry-core>=1.0.0", "poetry-dynamic-versioning"]
build-backend = "poetry_dynamic_versioning.backend"

[tool.poetry.group.development]
optional = true

[tool.poetry.group.development.dependencies]
pyScss = "^1.2.0"
Jinja2 = "<3.1"
sphinx = ">= 1.8.5, < 4"
sphinx_rtd_theme = "^0.1.6"
lowdown = "^0.1.0"
black = "==23.1.0"

[tool.poetry.group.test]
optional = true

[tool.poetry.group.test.dependencies]
pytest = "^2.3.5"

[tool.poetry-dynamic-versioning]
enable = true
vcs = "git"
style = "pep440"
latest-tag = true

[tool.poetry-dynamic-versioning.substitution]
files=["ftrack_connect_pipeline_harmony/_version.py"]
