# Action to release a package for Connect

name: 'Connect plugin build and release'
description: "Action that builds and releases a Connect plugin based on setuptools"
inputs:
  package:
    required: true
    description: The package to build the plugin for
  tag:
    required: true
    description: The tag to release
  suffix:
    required: true
    description: The suffix to append to the plugin filename
  pre:
    required: true
    description: Whether or not this is a pre-release
  deleteprevious:
    required: true
    description: Whether or not to delete the previous release
  token:
    required: true
    description: The GH token
  deploy_aws:
    required: true
    description: Deploy to AWS or not
  aws_key_id:
    required: true
    description: The AWS key ID to use
  aws_secret_access_key:
    required: true
    description: The AWS secret access key to use

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v4
      with:
        python-version: '3.7'
    - name: Fetch tags
      run: |
        git fetch -a -t --force
      shell: bash
    # Delete previous release and tag
    - uses: ClementTsang/delete-tag-and-release@v0.3.1
      if: ${{ inputs.deleteprevious == 'true' }}
      with:
        delete_release: true # default: false
        tag_name: ${{ inputs.tag }} # tag name to delete
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
    - name: Failsafe delete previous releases & tags, including drafts, matching tag pattern
      if: ${{ inputs.deleteprevious == 'true' }}
      shell: bash
      run: |
        gh release list --limit 100 | sed 's/|/ /' | awk '{print $1, $8}' | grep ${{ inputs.tag }} | while read -r line; do echo Deleting previous release: $line; gh release delete -y "$line" && git tag -d "$line" && git push origin --delete "$line"; done
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
      continue-on-error: true
    # TODO: Do a diff on release notes and supply with release body
    # Create pre-release
    - name: Create pre-release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ inputs.token }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ inputs.tag }}
        release_name: ${{ inputs.tag }}
        body: |
          Auto-generated pre-release on PR
          
          User: **${{ github.actor }}**
          Ref: **${{ github.ref }}**
          Commit: **${{ github.sha }}**
          
          Please check release notes for more information.
        prerelease: ${{ inputs.pre }}
    - name: Restore pants build from cache
      uses: actions/cache/restore@v3
      with:
        path: dist
        key: pants-dist-${{github.sha}}
        fail-on-cache-miss: true
        enableCrossOsArchive: true
    - name: Build Connect plugin
      run: |
        cd dist
        tar -xzvf ftrack-${{ inputs.package }}*.tar.gz
        cd $(ls -d ftrack-${{ inputs.package }}*/|head -n 1)
        python setup.py build_plugin
        mv -v build/*.zip ../
      shell: bash
    - name: Retrieve zipball filename
      run: |
        cd dist
        echo "PLUGIN_ZIPBALL=$(ls -f *.zip)" >> $GITHUB_ENV
      shell: bash
    - name: Append suffix
      if: ${{ inputs.suffix != '' }}
      run: |
        cd dist
        PLUGIN_ZIPBALL_PLATFORM=$(echo ${{ env.PLUGIN_ZIPBALL }} | sed 's/.zip/-${{ inputs.suffix }}.zip/')
        mv ${{ env.PLUGIN_ZIPBALL }} $PLUGIN_ZIPBALL_PLATFORM
        echo "PLUGIN_ZIPBALL=$PLUGIN_ZIPBALL_PLATFORM" >> $GITHUB_ENV
      shell: bash
    - uses: xresloader/upload-to-github-release@main
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
      with:
        file: "dist/${{ env.PLUGIN_ZIPBALL }}"
        release_id: ${{ steps.create_release.outputs.id }}
        overwrite: true
        verbose: true
        draft: false
    #  Upload non PR release artifact to S3 making it available via download.ftrack.com
    # (caching disabled for *0.0.0*.zip)
    - name: S3 upload
      if: ${{ inputs.deploy_aws == 'true' }}
      run: |
        aws --version
        aws s3 cp dist/${{ env.PLUGIN_ZIPBALL }} s3://ftrack-public-content/ftrack-connect/integrations/
      env:
        AWS_ACCESS_KEY_ID: ${{ inputs.aws_key_id }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.aws_secret_access_key }}
        AWS_DEFAULT_REGION: 'eu-central-1'
      shell: bash


