[project]
name = "ftrack.tool.session"
version = "0.1.0"
description = "Add your description here"
authors = [{name = "ftrack Integrations Team", email = "integrations@backlight.co"}]
readme = "README.md"
requires-python = ">=3.11, <3.12"
dependencies = [
    "click>8.0",
    "ftrack-library-session>=0.1.0",
]

[project.scripts]
session = "ftrack.tool.session.cli:session"

[project.entry-points."connect.plugins"]
session = "ftrack.tool.session.cli:session"

[tool.uv.sources]
ftrack-library-session = { path = "../../library/session", editable = true }

