[tool.poetry]
name = "ftrack-common-tool-configs-extension"
version = "2.0.0rc1"
description='ftrack common tool-configs extension'
authors = ["ftrack Integrations Team <integrations@backlight.co>"]
readme = "README.md"
packages = [{include = "ftrack_framework_common_tool_configs", from = "source"}]
license = "Apache-2.0"
homepage = "https://ftrack.com"
repository = "https://github.com/ftrackhq/integrations"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.dependencies]
python = ">= 3.7, < 3.8"
#ftrack
ftrack-constants = "2.0.0rc1"
ftrack-utils = "2.0.0rc1"

