type: pipeline-config
configs:
  - type: launch_config
    label: Maya
    icon: maya_{version}
    windows:
      path: "C:\\Program Files\\Autodesk\\Maya*\\bin\\maya_(?P<version>\\d{4}).exe"
    linux:
      path: "C:\\Program Files\\Autodesk\\Maya*\\bin\\maya_(?P<version>\\d{4}).exe"
    macos:
      path: "C:\\Program Files\\Autodesk\\Maya*\\bin\\maya_(?P<version>\\d{4}).exe"

  - type: tool-config
    label: Maya
    icon: maya_{version}
    windows:
      path: "C:\\Program Files\\Autodesk\\Maya*\\bin\\maya_(?P<version>\\d{4}).exe"
    linux:
      path: "C:\\Program Files\\Autodesk\\Maya*\\bin\\maya_(?P<version>\\d{4}).exe"
    macos:
      path: "C:\\Program Files\\Autodesk\\Maya*\\bin\\maya_(?P<version>\\d{4}).exe"