# :coding: utf-8
# :copyright: Copyright (c) 2024 ftrack

import click
from ftrack.library.authenticate.util.identifier import generate_credential_identifier
from ftrack.library.authenticate.helper.credential import CredentialProvider

from ftrack.library.session.session import SessionProvider


@click.group()
def session():
    """
    Launcher CLI tool
    """
    pass


@session.command()
@click.option(
    "--credential-identifier",
    type=str,
    default=lambda: generate_credential_identifier(),
    show_default="Generated by generate_credential_identifier()",
    help="Unique identifier for the credentials. Defaults to a <user_name>@<server_url> identifier.",
)
def start_event_hub(credential_identifier):
    """
    Start the event hub thread.

    :param credential_identifier: Unique identifier for the credentials.
    """
    try:
        credential_provider = CredentialProvider(credential_identifier)

        session_provider = SessionProvider(credential_provider)
        # TODO: we should probably not start the event hub in a new thread ere, but instead in a new process?. We have to review this.
        session = session_provider.load_session(auto_connect_event_hub=True)
        click.echo(f"Event hub thread started for session {session}")

    except click.BadParameter as e:
        click.echo(f"Error: {e}", err=True)
    except Exception as e:
        click.echo(f"An unexpected error occurred: {e}", err=True)
