paths:
  windows:
    resource_path: %appdata%
connect:
  marketplace-source: #repo branch tag in git
  resource_path: {paths.{runtime.platform_full}.resource_path}/{runtime.args.workspace}
  # supporting .env files