# On release creation:
#  - Build and publishes libraries to PyPi or
#  - Building Connect plugin artifacts and upload them to the release

name: CI-RELEASE

on:
  release:
    types: [created]


jobs:

  # Set the environment variables for the rest of release workflow
  set-variables:
    runs-on: ubuntu-latest
    outputs:
      folder: ${{ env.FOLDER }}
      package: ${{ env.PACKAGE }}
      version: ${{ env.VERSION }}
      tag: ${{ env.TAG }}
    steps:
      - uses: actions/checkout@v3
      - name: set environments on full release
        shell: bash
        run: |
          echo "PACKAGE=$(echo ${{ github.ref }} | cut -d/ -f 3-3)" >> $GITHUB_ENV
          echo "VERSION=$(echo ${{ github.ref }} | cut -d/ -f 4-4)" >> $GITHUB_ENV
          echo "TAG=$(echo ${{ github.ref }} | cut -d/ -f 3-4)" >> $GITHUB_ENV
      - name: set apps folder
        if: ${{ env.PACKAGE == 'connect' }}
        shell: bash
        run: |
          echo "FOLDER=apps/${{ env.PACKAGE }}" >> $GITHUB_ENV
      - name: set installers folder
        if: ${{ env.PACKAGE == 'connect-installer' }}
        run: echo Not supported by this CI && exit 1
      - name: set lib folder
        if: ${{ env.PACKAGE == 'constants' || env.PACKAGE == 'framework-core' || env.PACKAGE == 'framework-qt' || env.PACKAGE == 'qt' || env.PACKAGE == 'qt-style' || env.PACKAGE == 'utils' }}
        shell: bash
        run: |
          echo "FOLDER=libs/${{ env.PACKAGE }}" >> $GITHUB_ENV
      - name: set projects folder
        if: ${{ env.PACKAGE == 'connect-publisher-widget' || env.PACKAGE == 'connect-timetracker-widget' || env.PACKAGE == 'framework-photoshop' || env.PACKAGE == 'nuke-studio' || env.PACKAGE == 'rv' }}
        shell: bash
        run: |
          echo "FOLDER=projects/${{ env.PACKAGE }}" >> $GITHUB_ENV
      - name: debug
        shell: bash
        run: |
          echo 'FOLDER: ${{ env.FOLDER }}'
          echo 'PACKAGE: ${{ env.PACKAGE }}'
          echo 'VERSION: ${{ env.VERSION }}'
          echo 'TAG: ${{ env.TAG }}'

  build-linux:
    name: Build platform independent artifacts, and Linux specific artifacts
    needs: set-variables
    concurrency:
      group: ci-${{ github.ref }}
    if: ${{ needs.set-variables.outputs.package != 'framework-photoshop' }}
    runs-on: ubuntu-latest
    outputs:
      to_pypi: ${{ needs.set-variables.outputs.to_pypi }}
      package: ${{ needs.set-variables.outputs.package }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.7'
      - name: install poetry
        shell: bash
        run: |
          pip install poetry==1.5.1
      - name: build style
        if: ${{ needs.set-variables.outputs.package == 'qt-style' }}
        shell: bash
        run: |
          pip install -r tools/requirements.txt
          python tools/build.py build_qt_resources libs/qt-style
      - name: poetry build
        shell: bash
        run: |
          cd ${{ needs.set-variables.outputs.folder }}
          poetry build
      - name: build standard connect plugin
        if: ${{ needs.set-variables.outputs.package == 'connect-publisher-widget' || needs.set-variables.outputs.package == 'connect-timetracker-widget' }}
        shell: bash
        run: |
          pip install -r tools/requirements.txt
          # Use --testpypi or --from_source to change where the deps are picked from
          python tools/build.py --remove_intermediate_folder build_connect_plugin ${{ needs.set-variables.outputs.folder }}
      - name: build nuke studio connect plugin
        if: ${{ needs.set-variables.outputs.package == 'nuke-studio' }}
        shell: bash
        run: |
          pip install -r tools/requirements.txt
          python tools/build.py --remove_intermediate_folder --include_resources resource/plugin,resource/application_hook build_connect_plugin ${{ needs.set-variables.outputs.folder }}
      - name: build rv connect plugin
        if: ${{ needs.set-variables.outputs.package == 'rv' }}
        shell: bash
        run: |
          cd projects/rv
          python build_rv_plugin.py resource/plugin /tmp/
          cd ../..
          pip install -r tools/requirements.txt
          python tools/build.py --remove_intermediate_folder --include_assets /tmp/ftrack-5.1.0.rvpkg build_connect_plugin ${{ needs.set-variables.outputs.folder }}
      - name: upload artifacts to release
        shell: bash
        run: |
          cd ${{ needs.set-variables.outputs.folder }}
          gh release upload ${{ needs.set-variables.outputs.tag }} dist/* --clobber
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload temp artifacts
        uses: actions/upload-artifact@v2
        if: ${{ needs.set-variables.outputs.to_pypi == 'true' }}
        with:
          name: dist
          path: ${{ needs.set-variables.outputs.folder }}/dist

  build-windows:
    name: Build Windows platform dependent artifacts
    needs: set-variables
    concurrency:
      group: ci-${{ github.ref }}
    if: ${{ needs.set-variables.outputs.package == 'framework-photoshop' }}
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.7'
      - name: install poetry
        shell: bash
        run: |
          pip install poetry==1.5.1
      - name: poetry build
        shell: bash
        run: |
          cd ${{ needs.set-variables.outputs.folder }}
          poetry build
      - name: build standard connect plugin
        shell: bash
        run: |
          pip install -r tools/requirements.txt
          python tools/build.py --remove_intermediate_folder build_connect_plugin ${{ needs.set-variables.outputs.folder }}
      - name: upload artifacts to release
        shell: bash
        run: |
          cd ${{ needs.set-variables.outputs.folder }}
          gh release upload ${{ needs.set-variables.outputs.tag }} dist/*  --clobber
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-mac:
    name: Build Mac platform dependent artifacts
    needs: set-variables
    concurrency:
      group: ci-${{ github.ref }}
    if: ${{ needs.set-variables.outputs.package == 'framework-photoshop' }}
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.7'
      - name: install poetry
        shell: bash
        run: |
          pip install poetry==1.5.1
      - name: poetry build
        shell: bash
        run: |
          cd ${{ needs.set-variables.outputs.folder }}
          poetry build
      - name: build standard connect plugin
        shell: bash
        run: |
          pip install -r tools/requirements.txt
          python tools/build.py --remove_intermediate_folder build_connect_plugin ${{ needs.set-variables.outputs.folder }}
      - name: build PS CEP extension
        if: ${{ needs.set-variables.outputs.package == 'framework-photoshop' }}
        shell: bash
        run: |
          # Install ZXPsign
          wget -c https://raw.github.com/Adobe-CEP/CEP-Resources/master/ZXPSignCMD/4.1.2/macOS/ZXPSignCmd-64bit.dmg  -O /tmp/ZXPSignCmd-64bit.dmg
          hdiutil attach /tmp/ZXPSignCmd-64bit.dmg
          ln -s /Volumes/ZXPSignCmd-64bit/ZXPSignCmd-64bit /usr/local/bin/ZXPSignCMD
          export ADOBE_CERTIFICATE_PASSWORD=${{ secrets.ADOBE_CERTIFICATE_PASSWORD }}
          python tools/build.py build_cep --remove_intermediate_folder ${{ needs.set-variables.outputs.folder }}
      - name: upload artifacts to release
        shell: bash
        run: |
          cd ${{ needs.set-variables.outputs.folder }}
          gh release upload ${{ needs.set-variables.outputs.tag }} dist/*  --clobber
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}