name: CI

on:
  push:
    branches: ["main", "*/story"]

jobs:
  release:
    name: Pre-release
    runs-on: ubuntu-latest
    outputs:
      release_id: ${{ steps.create_pre_release.outputs.id }}
      source_tag: ${{ env.SOURCE_TAG }}
      source_hash: ${{ env.SOURCE_HASH }}
    steps:
      - uses: actions/checkout@v3
      - name: Set envs
        run: |
          git fetch -a
          git tag | sort
          echo "SOURCE_TAG=$(git tag | sort | tail -n 1 | cut -d- -f -1)" >> $GITHUB_ENV
          echo "SOURCE_HASH=$(echo ${{github.sha}} | cut -b -7)" >> $GITHUB_ENV
      - name: Create pre release
        id: create_pre_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ env.SOURCE_TAG }}-${{ env.SOURCE_HASH }}
          release_name: PR test release ${{ env.SOURCE_TAG }}-${{ env.SOURCE_HASH }}(${{ github.ref }})
          body: |
            Please check PR for details.
          draft: false
          prerelease: true
  build-framework:
    name: Build framework plugins for Connect
    needs: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.7'
      - uses: pantsbuild/actions/init-pants@v4-scie-pants
        # This action bootstraps pants and manages 2-3 GHA caches.
        # See: github.com/pantsbuild/actions/tree/main/init-pants/
        with:
          # v0 makes it easy to bust the cache if needed
          # just increase the integer to start with a fresh cache
          gha-cache-key: v0
          # The Python backend uses named_caches for Pip/PEX state,
          # so it is appropriate to invalidate on lockfile changes.
          named-caches-hash: ${{ hashFiles('python-default.lock') }}
          # If you're not using a fine-grained remote caching service (see https://www.pantsbuild.org/docs/remote-caching),
          # then you may also want to preserve the local Pants cache (lmdb_store). However this must invalidate for
          # changes to any file that can affect the build, so may not be practical in larger repos.
          # A remote cache service integrates with Pants's fine-grained invalidation and avoids these problems.
          cache-lmdb-store: 'true'  # defaults to 'false'
          # Note that named_caches and lmdb_store falls back to partial restore keys which
          # may give a useful partial result that will save time over completely clean state,
          # but will cause the cache entry to grow without bound over time.
          # See https://pants.readme.io/docs/using-pants-in-ci for tips on how to periodically clean it up.
          # Alternatively you change gha-cache-key to ignore old caches.
      - name: Checkout and set envs
        run: |
          git fetch -a
          git checkout ${{ github.sha }}
          echo "SOURCE_TAG=${{ needs.release.outputs.source_tag }}" >> $env:GITHUB_ENV
          echo "SOURCE_HASH=${{ needs.release.outputs.source_hash }}" >> $env:GITHUB_ENV
      - name: Check BUILD files
        if: false
        run:  |
          pants tailor --check update-build-files --check ::
      - name: Lint and typecheck
        if: false
        run: | 
          pants lint check ::
      - name: Test
        if: false
        run: |
          pants test ::
      - name: Package / Run
        run: |
          # We also smoke test that our release process will work by running `package`.
          pants package ::
      - name: Build framework core Connect plugin
        run: |
          cd dist
          tar -xzvf framework-core*.tar.gz
          cd $(ls -d framework-core*/|head -n 1)
          python setup.py build_plugin
          mv build/*.zip ../
      - name: Build framework QT Connect plugin
        run: |
          cd dist
          tar -xzvf framework-qt*.tar.gz
          cd $(ls -d framework-qt*/|head -n 1)
          python setup.py build_plugin
          mv build/*.zip ../
      - name: Build framework Maya Connect plugin
        run: |
          cd dist
          tar -xzvf framework-maya*.tar.gz
          cd $(ls -d framework-maya*/|head -n 1)
          python setup.py build_plugin
          mv build/*.zip ../
      - uses: xresloader/upload-to-github-release@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: "dist/*.zip"
          release_id: ${{ needs.release.outputs.release_id }}
          overwrite: true
          verbose: true