# Create the v0.0.0-latest pre-release on push/merge to main, be it on a PR merge,
# direct push or a release tag push.
# Cleans up old tags and releases.

name: pre-release

on:
  workflow_call:
    inputs:
      changed:
        required: true
        type: string

jobs:
  pre-release:
    runs-on: ubuntu-latest

#    strategy:
#      matrix:
#        package: [application-launcher, connect-action-launcher-widget, connect-plugin-manager, framework-core, framework-qt, framework-maya, framework-nuke, framework-houdini, framework-3dsmax, connect-timetracker-widget, nuke-studio, rv]
#        os: [ubuntu-latest]
#        include:
#          - package: framework-unreal
#            os: windows-latest
#          # Add new packages here
#    runs-on: ${{ matrix.os }}
    steps:
      - name: test
        run: echo "${{inputs.changed}}"
      - name: test_en
        run: echo "${{ env.CHANGED }}"
#      - name: Check out repository
#        if: ${{ contains(needs.pants-build.outputs.changed,matrix.package) }}
#        uses: actions/checkout@v3
#      - name: Run release action
#        if: ${{ contains(needs.pants-build.outputs.changed,matrix.package) }}
#        uses: ./.github/actions/connect-release
#        with:
#          package: ${{ matrix.package }}
#          tag: ${{ matrix.package }}/v0.0.0-latest
#          suffix: ${{ matrix.suffix }}
#          deleteprevious: true
#          prerelease: true
#          token: ${{ secrets.GITHUB_TOKEN }}
#          aws_key_id: ${{ secrets.S3_ACCESS_KEY }}
#          aws_secret_access_key: ${{ secrets.S3_SECRET_ACCESS_KEY}}