# Create the v0.0.0-latest pre-release on push/merge to main, be it on a PR merge,
# direct push or a release tag push.
# Cleans up old tags and releases.

name: pre-release

on:
  workflow_call:
    inputs:
      changed:
        required: true
        type: string
      tag_type:
        required: true
        type: string
      deploy_aws:
        required: true
        type: boolean
    secrets:
      aws_key_id:
        required: true
      aws_secret_access_key:
        required: true

jobs:
  pre-release:
    strategy:
      matrix:
        # Add new packages here
        package: [application-launcher, connect-action-launcher-widget, connect-plugin-manager, framework-core, framework-qt, framework-maya, framework-nuke, framework-houdini, framework-3dsmax, connect-timetracker-widget, nuke-studio, rv]
        os: [ubuntu-latest]
        suffix: ['']
        include:
          - package: framework-unreal
            os: windows-latest
            suffix: 'win'
          # Add platform dependent packages here
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out repository
        if: ${{ contains(inputs.changed,matrix.package) }}
        uses: actions/checkout@v3
      - name: Run release action
        if: ${{ contains(inputs.changed,matrix.package) }}
        uses: ./.github/actions/connect-release
        with:
          package: ${{ matrix.package }}
          tag: ${{ matrix.package }}/v0.0.0-${{inputs.tag_type}}
          suffix: ${{ matrix.suffix }}
          deleteprevious: true
          prerelease: true
          deploy_aws: ${{inputs.deploy_aws}}
          token: ${{ secrets.GITHUB_TOKEN }}
          aws_key_id: ${{ secrets.aws_key_id }}
          aws_secret_access_key: ${{ secrets.aws_secret_access_key }}
