# Create the v0.0.0-pr<number> pre-release on PR update.
# Cleans up old tags and releases for the same PR.

name: CI-PR

# Prevent concurrent runs of this workflow due to the pants cache being shared between them.
concurrency: pants_ci

on:
#  push:
#    branches: [ "backlog/ci" ] #TODO: remember to remove pushand branches
  pull_request:
    types:
#      - opened
#      - edited
#      - synchronize
      - closed

jobs:
  pants-build:
    uses: ./.github/workflows/pants-build.yml
    with:
      pre_tag: false
      check_changed: true

  pre-release:
    needs: pants-build
    uses: ./.github/workflows/pre-release.yml
    with:
      changed: ${{needs.pants-build.outputs.changed}}
      tag_type: "pr${{ github.event.number }}"

