# Create the v0.0.0-pr<number> pre-release on PR update.
# Cleans up old tags and releases for the same PR.

name: CI-PR

# Prevent concurrent runs of this workflow due to the pants cache being shared between them.
concurrency: pants_ci

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  pants-build:
    uses: ./.github/workflows/pants-build.yml
    with:
      pre_tag: false
      check_changed: true

  # Have to call connect release directly due to problems passing on AWS credentials
  pre-release:
    needs: pants-build
    uses: ./.github/workflows/pre-release.yml
    with:
      changed: ${{needs.pants-build.outputs.changed}}
      tag_type: "pr${{ github.event.number }}"
      deploy_aws: false
    secrets:
      aws_key_id: ${{ secrets.S3_ACCESS_KEY }}
      aws_secret_access_key: ${{ secrets.S3_SECRET_ACCESS_KEY }}
