# Create the v0.0.0dev<number> pre-release on PR update.
# Cleans up old tags and releases for the same PR.

name: CI-PR

# Prevent concurrent runs of this workflow due to the pants cache being shared between them.
concurrency: pants_ci

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  matrix_prep:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - id: set-matrix
        run: |
          matrix=$(jq --arg package "framework-maya" 'map(. | select((.package=="framework-maya")))' tools/deployment_tools/gh_repo_matrix.json) 
          echo $matrix
          echo "matrix={\"include\":$(echo $matrix)}" >> $GITHUB_OUTPUT
#  pants-build:
#    uses: ./.github/workflows/pants-build.yml
#    with:
#      full_release: false
#      check_changed: true
#      tag_type: "dev${{ github.event.number }}"
#
#  pre-release:
#    needs: pants-build
#    uses: ./.github/workflows/release.yml
#    with:
#      changed: ${{needs.pants-build.outputs.changed}}
#      pre: true
#      tag: "0.0.0dev${{ github.event.number }}"
#      deploy_aws: false
#    secrets:
#      aws_key_id: ${{ secrets.S3_ACCESS_KEY }}
#      aws_secret_access_key: ${{ secrets.S3_SECRET_ACCESS_KEY }}
