# Create the v0.0.0-latest pre-release on push/merge to main, be it on a PR merge,
# direct push or a release tag push.
# Cleans up old tags and releases.

name: CI-MERGE

# Prevent concurrent runs of this workflow due to the pants cache being shared between them.
concurrency: pants_ci

on:
  push:
    branches: ["main", "backlog/ci"] #TODO: remember to remobe backlog/ci

jobs:
#  pants-build:
#    uses: ./.github/workflows/pants-build.yml
#    with:
#      pre_tag: false
#      check_changed: true
#
#  pre-release:
#    needs: pants-build
#    uses: ./.github/workflows/pre-release.yml
#    with:
#      changed: ${{needs.pants-build.outputs.changed}}
#      tag_type: "latest"

  deploy-docs:
    #needs: pants-build
    uses: ./.github/workflows/deploy-docs.yml
    with:
      changed: test #${{needs.pants-build.outputs.changed}}
      #destination: ./latest
