# Create the v0.0.0rc pre-release on push/merge to main, be it on a PR merge or direct push.
# Cleans up old tags and releases.

name: CI-MERGE

# Prevent concurrent runs of this workflow due to the pants cache being shared between them.
concurrency: pants_ci

on:
  push:
    branches: ["dummy"] # Disable CI - do not trigger

jobs:

  # Run Pants to evaluate which packages have changed.
  pants-build:
    uses: ./.github/workflows/pants-build.yml
    with:
      full_release: false
      check_changed: true
      version: "v0.0.0rc"

  # Create a pre-release for the packages that have changed.
  pre-release:
    needs: pants-build
    uses: ./.github/workflows/release.yml
    with:
      changed: ${{needs.pants-build.outputs.changed}}
      pre: true
      version: ${{needs.pants-build.outputs.version}}
      deploy_aws: true
    secrets:
      aws_key_id: ${{ secrets.S3_ACCESS_KEY }}
      aws_secret_access_key: ${{ secrets.S3_SECRET_ACCESS_KEY }}

  deploy-docs:
      needs: pants-build
      uses: ./.github/workflows/deploy-docs.yml
      with:
        changed: ${{needs.pants-build.outputs.changed}}
        build_index: false
        is_rc: true
