# Create the v0.0.0-latest pre-release on push/merge to main, be it on a PR merge,
# direct push or a release tag push.
# Cleans up old tags and releases.

name: CI-MERGE

# Prevent concurrent runs of this workflow due to the pants cache being shared between them.
concurrency: pants_ci

on:
  push:
    branches: ["main"]

jobs:
  pants-build:
    name: Build with Pants and probe which packages has changed
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.pantsBuild.outputs.changed }}
    steps:
      - id: pantsBuild
        uses: ./.github/actions/pants-build@backlog/ci #lluisFtrack/test_monorepo_ci/.github/actions/pants-build@backlog/ci #./.github/actions/pants-build@backlog/ci

#  pre-release:
#    needs: pants-build
#    uses: ./.github/workflows/pre-release.yml
#    with:
#      changed: pants-build.outputs.changed

  deploy-docs:
    uses: ./.github/workflows/deploy-docs.yml
    with:
      changed: pants-build.outputs.changed
