# Updates the _version.py file with the correct version

name: update-packages-version

on:
  workflow_call:
    inputs:
      changed:
        required: true
        type: string
      version:
        required: false
        type: string
        default: 0.0.0
    outputs:
      os:
        description: "The first output string"
        value: ${{ jobs.pre-release.outputs.os }}
      suffix:
        description: "The first output string"
        value: ${{ jobs.pre-release.outputs.suffix }}

jobs:
  pre-release:
    strategy:
      matrix:
        # Add new packages here
        package: [application-launcher, connect-action-launcher-widget, connect-plugin-manager, framework-maya, framework-nuke, framework-houdini, framework-3dsmax, connect-timetracker-widget, nuke-studio, rv]
        os: [ubuntu-latest]
        folder: [projects]
        suffix: ['']
        include:
          - package: framework-unreal
            os: windows-latest
            suffix: 'win'
            folder: projects
          - package: framework-core
            os: ubuntu-latest
            folder: libs
            suffix: ''
          - package: framework-qt
            os: ubuntu-latest
            folder: libs
            suffix: ''
          # Add platform dependent packages here
    runs-on: ${{ matrix.os }}
    outputs:
      os: ${{ env.OS }}
      suffix: ${{ env.SUFFIX }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all commits so we can calculate diff properly

      - name: Run set internal version action
        if: ${{ contains(inputs.changed,matrix.package) }}
        uses: ./.github/actions/update-package-version
        with:
          package: ${{ matrix.package }}
          version: ${{ inputs.version }}
          folder: ${{ matrix.folder }}
      - name: Set output variables
        shell: bash
        run: |
          echo "OS=${{ matrix.os }}" >> $GITHUB_ENV
          echo "SUFFIX=${{ matrix.suffix }}" >> $GITHUB_ENV
